# Generated by Django 3.0.3 on 2020-02-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccupationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.HousingType')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('annual_income', models.PositiveIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Gender')),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.Household')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.MaritalStatus')),
                ('occupation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.OccupationType')),
                ('spouse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FamilyMember')),
            ],
        ),
    ]
